/**
 * zipExporter.js — ZIP package generation
 * Uses JSZip loaded from CDN to create the downloadable archive.
 *
 * Output structure:
 *   menu/
 *     index.html    (standalone, inline CSS+JS, fetches menu.json)
 *     menu.json     (clean data)
 *     assets/       (uploaded local images only)
 */

window.ZipExporter = (() => {
  const JSZIP_CDN = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';

  function loadJSZip() {
    if (typeof JSZip !== 'undefined') return Promise.resolve();
    return new Promise((resolve, reject) => {
      const script = document.createElement('script');
      script.src = JSZIP_CDN;
      script.onload = resolve;
      script.onerror = () => reject(new Error('Could not load JSZip. Check your internet connection.'));
      document.head.appendChild(script);
    });
  }

  /**
   * Export the current menu as a ZIP file
   */
  async function exportZip(menuData) {
    await loadJSZip();

    const zip = new JSZip();
    const menuFolder = zip.folder('menu');

    // 1. Generate standalone index.html (contains all HTML, CSS, JS, and embedded menu content)
    const html = MenuRenderer.generateHTML(menuData);
    menuFolder.file('index.html', html);

    // 2. Add local image assets (if any)
    const localImages = HtmlExporter.collectLocalImages(menuData);
    if (localImages.length > 0) {
      const assetsFolder = menuFolder.folder('assets');
      for (const img of localImages) {
        const bytes = HtmlExporter.dataUrlToUint8Array(img.dataUrl);
        const filename = img.filename || img.path.split('/').pop();
        assetsFolder.file(filename, bytes, { binary: true });
      }
    }

    // 4. Add a README
    const restaurantName = menuData.restaurant?.name || 'My Menu';
    const readme = `# ${restaurantName} — Digital Menu

Generated by Digital Menu Builder.

## Files

- \`index.html\` — The menu page (standalone HTML with inline CSS + JS)
- \`menu.json\` — Menu data (edit this to update content)
- \`assets/\` — Uploaded images (if any)

## How to use

### Option 1: Open locally
Double-click \`index.html\` to open in your browser.

> Note: Some browsers block \`fetch()\` on local files. Use a simple HTTP server:
> \`python -m http.server 8080\` then visit http://localhost:8080/menu/

### Option 2: Host on GitHub Pages
1. Create a public GitHub repository
2. Upload all files from this folder to the repository root
3. Go to Repository Settings → Pages → Deploy from branch (main, root)
4. Your menu will be live at: https://[username].github.io/[repo-name]/

### Updating the menu
- Edit \`menu.json\` directly to update content (names, prices, descriptions)
- Or re-export from the Digital Menu Builder and replace the files

## Architecture
- \`index.html\` loads \`menu.json\` via \`fetch('menu.json')\`
- No backend required — works as a static site
- Compatible with GitHub Pages, Netlify, Vercel, and any static hosting
`;
    menuFolder.file('README.md', readme);

    // 5. Download the ZIP
    const blob = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 }
    });

    const slugName = IdUtils.slug(restaurantName) || 'menu';
    const filename = `${slugName}-menu-${new Date().toISOString().slice(0,10)}.zip`;

    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);

    return { filename, hasLocalImages: localImages.length > 0, imageCount: localImages.length };
  }

  return { exportZip };
})();
